### ISSUE TITLE
1.3.0 Error with package install: Unhandled exception while executing module: Cannot index into a null array

### ISSUE THREAD

**Issue by opoplawski** [chocolatey/chocolatey-ansible#90]
### What You Are Seeing?
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was:    at System.Management.Automation.CommandProcessorBase.Complete()
fatal: [FQDN]: FAILED! => {"changed": false, "msg": "Unhandled exception while executing module: Cannot index into a null array."}
```

### What is Expected?
No error
### How Did You Get This To Happen? (Steps to Reproduce)
```
- hosts: server
  ignore_unreachable: yes
  gather_facts: no
  tasks:
    # winlogbeat 7.13+ is not compatible with OpenSearch
    - name: Update winlogbeat-oss
      win_chocolatey:
        name:
          - winlogbeat-oss
        version: 7.12.1
        pinned: yes
        state: latest
      notify: restart winlogbeat
```
This seems to only happen on certain remote hosts.

### System Details

* OS Build (In PowerShell run `[System.Environment]::OSVersion.version.tostring()`): 10.0.17763.0
* Windows PowerShell version (Run: `$PSVersionTable`):
```
Name                           Value                                                              
----                           -----                                                              
PSVersion                      5.1.17763.2931                                                     
PSEdition                      Desktop                                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                            
BuildVersion                   10.0.17763.2931                                                    
CLRVersion                     4.0.30319.42000                                                    
WSManStackVersion              3.0                                                                
PSRemotingProtocolVersion      2.3                                                                
SerializationVersion           1.1.0.1  
```
* Chocolatey version (Run `choco --version`): 1.1.0

winlogbeat-oss is already installed:
```
Chocolatey v1.1.0
choco-cleaner 0.0.8.4
chocolatey-core.extension 1.3.5.1
chocolatey-dotnetfx.extension 1.0.1
dotnetfx 4.8.0.20190930
git.install 2.35.2
KB2919355 1.0.20160915
KB2919442 1.0.20160915
netfx-4.8 4.8.0.20190930
nxlog 2.10.2150
winlogbeat-oss 7.12.1
zabbix-agent.install 6.0.2
11 packages installed.
```

### Output Log
<details>
<summary>Full Log Output</summary>

<p>

```
redirecting (type: modules) ansible.builtin.win_chocolatey to chocolatey.chocolatey.win_chocolatey
[task 62051] 10:05:53.537503 D ansible_mitogen.affinity: CPU mask for WorkerProcess: 0x000001
redirecting (type: modules) ansible.builtin.win_chocolatey to chocolatey.chocolatey.win_chocolatey
Using module file /usr/share/ansible/collections/ansible_collections/chocolatey/chocolatey/plugins/modules/win_chocolatey.ps1
Pipelining is enabled.
<nwra-ca1.ad.nwra.com> ESTABLISH WINRM CONNECTION FOR USER: None on PORT 5986 TO nwra-ca1.ad.nwra.com
EXEC (via pipeline wrapper)
The full traceback is:
Cannot index into a null array.
At line:122 char:17
+ $chocoCommand = Install-Chocolatey @installParams
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Install-Chocolatey], RuntimeException
    + FullyQualifiedErrorId : NullArray,Install-Chocolatey

ScriptStackTrace:
at Install-Chocolatey, <No file>: line 1087
at <ScriptBlock>, <No file>: line 122

System.Management.Automation.RuntimeException: Cannot index into a null array.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
fatal: [nwra-ca1.ad.nwra.com]: FAILED! => {
    "changed": false,
    "msg": "Unhandled exception while executing module: Cannot index into a null array."
}
```
</p>

</details>

**Comment by opoplawski** [comment]
Also happens with a simple task:
```
    - name: Update nxlog
      win_chocolatey:
        name:
          - nxlog
        state: latest
```

**Comment by opoplawski** [comment]
Downgrading to chocolatey-chocolatey 1.2.0 from 1.3.0 seems to resolve the issue.

**Comment by vexx32** [comment]
I'm not entirely sure why, but looking at the logs the likely place this error gets thrown from would be here:
https://github.com/chocolatey/chocolatey-ansible/blob/85ee7fd4375bdbc506f6d9cfffbb81817565f530/chocolatey/plugins/module_utils/Packages.psm1#L1086

It should most likely be moved into the try/catch block below... seems to indicate that for some reason on these nodes, the actual Chocolatey installed package version can't be determined.

On the affected / problematic nodes, can you run a `choco list -lo` and see if `chocolatey` itself is listed in the result for those nodes?

**Comment by opoplawski** [comment]
It does seem to appear:
```
Chocolatey v1.1.0
choco-cleaner 0.0.8.4
chocolatey-compatibility.extension 1.0.0
chocolatey-core.extension 1.4.0
chocolatey-dotnetfx.extension 1.0.1
dotnetfx 4.8.0.20220524
git.install 2.37.1
KB2919355 1.0.20160915
KB2919442 1.0.20160915
netfx-4.8 4.8.0.20190930
nxlog 2.10.2150
winlogbeat-oss 7.12.1
zabbix-agent.install 6.0.5
12 packages installed.
```

**Comment by opoplawski** [comment]
Ah, I see, no "chocolatey" does not appear.  A working node does have it:
```
Chocolatey v1.1.0
choco-cleaner 0.0.8.4
chocolatey 1.1.0
chocolatey-compatibility.extension 1.0.0
chocolatey-core.extension 1.4.0
chocolatey-dotnetfx.extension 1.0.1
KB2919355 1.0.20160915
KB2919442 1.0.20160915
netfx-4.8 4.8.0.20190930
nxlog 2.10.2150
winlogbeat-oss 7.12.1
zabbix-agent.install 6.0.5
11 packages installed.
```

**Comment by opoplawski** [comment]
I did a `choco install chocolatey -y --force` on a problematic machine and now it appears an win_package works.  Not sure how those machines got into that state.

**Comment by vexx32** [comment]
Yeah that's a bit of an oddity. I think we can at least get the module to a state where it will warn but continue anyway in this circumstance which feels appropriate. Thanks for reporting! 💖
